---
#################
# Build default #
#################
tmp_dir: /tmp

build_overrides:
  - section: DEFAULT
    option: push
    value: true
  - section: DEFAULT
    option: registry
    value: "{{ docker_registry_ip }}:{{ docker_registry_port }}"
  - section: DEFAULT
    option: base
    value: "{{ kolla_vm_os_distro }}"
  - section: DEFAULT
    option: install_type
    value: "{{ kolla_install_type }}"
  - section: DEFAULT
    option: tag
    value: "{{ kolla_build_tag }}"
  - section: DEFAULT
    option: debug
    value: "{{ kolla_build_debug }}"
  - section: DEFAULT
    option: namespace
    value: "{{ kolla_image_namespace }}"
  - section: DEFAULT
    option: retries
    value: 0
  - section: profiles
    option: myprofile
    value: chrony,cinder,cron,designate,elasticsearch,etcd,fluentd,glance,haproxy,heat,horizon,influxdb,iscsi,keepalived,keystone,kibana,kolla-toolbox,magnum,mariadb,memcached,mistral,mongodb,neutron,nova-,octavia,openvswitch,qdrouterd,rabbitmq,redis,searchlight,skydive,tacker,telegraf,tgtd,zookeeper,zun
