---
- name: Add Docker CentOS repo
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: True
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_distribution|lower == "centos"

- name: Add Docker Ubuntu repo signing keys
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  when: ansible_distribution|lower == "ubuntu"

- name: Add Docker Ubuntu repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  when: ansible_distribution|lower == "ubuntu"

- name: Install Docker-ce package
  package:
    name: "docker-ce"
    state: latest

- name: Create drop-in unit directory for docker.service
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Enable CentOS insecure registry
  lineinfile:
    path: /etc/sysconfig/docker
    create: True
    line: "INSECURE_REGISTRY='--insecure-registry {{ docker_registry_ip }}:{{ docker_registry_port }}'"
  when: ansible_distribution|lower == "centos"

- name: Create the CentOS drop-in unit file
  lineinfile:
    path: /etc/systemd/system/docker.service.d/docker.conf
    create: True
    line: |
      [Service]
      EnvironmentFile=/etc/sysconfig/docker
      ExecStart=
      ExecStart=/usr/bin/dockerd $INSECURE_REGISTRY
  when: ansible_distribution|lower == "centos"

- name: Enable Ubuntu insecure registry
  lineinfile:
    path: /etc/default/docker
    create: True
    state: present
    line: "DOCKER_OPTS='--insecure-registry {{ docker_registry_ip }}:{{ docker_registry_port }}'"
  when: ansible_distribution|lower == "ubuntu"

- name: Create the Ubuntu drop-in unit file
  lineinfile:
    path: /etc/systemd/system/docker.service.d/docker.conf
    create: True
    line: |
      [Service]
      EnvironmentFile=-/etc/default/docker
      ExecStart=
      ExecStart=/usr/bin/dockerd $DOCKER_OPTS
  when: ansible_distribution|lower == "ubuntu"

- name: Restart Docker service
  systemd:
    name: docker
    daemon_reload: True
    state: restarted
    enabled: True

- name: Add current user to Docker group
  user:
    name: "{{ os_default_user }}"
    groups: docker
    append: True
