---
- name: Ensure source code checkout directory exists
  become: true
  file:
    path: "{{ tmp_dir }}/kolla"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone Kolla repository
  git:
    repo: https://github.com/openstack/kolla
    dest: "{{ tmp_dir }}/kolla"

- name: Install Kolla
  become: true
  pip:
    name: "file://{{ tmp_dir }}/kolla"

- name: Generate kolla-build.conf file
  command: "tox -e genconfig"
  args:
    chdir: "{{ tmp_dir }}/kolla"
    creates: "{{ tmp_dir }}/kolla/etc/kolla/kolla-build.conf"

- name: Ensure the Kolla Ansible configuration directores exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750
  with_items:
    - "{{ kolla_config_path }}"
    - "{{ kolla_config_path }}/inventory"

- name: Copy kolla-build.conf file to Kolla conf dir
  copy:
    src: "{{ tmp_dir }}/kolla/etc/kolla/kolla-build.conf"
    dest: "{{ kolla_config_path }}/kolla-build.conf"
    remote_src: true
  tags: build

- name: Override build variables in kolla-build.conf
  ini_file:
    path: "{{ kolla_config_path }}/kolla-build.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ build_overrides }}"
  tags: build

- name: Copy template-overrides.j2 file to Kolla dir [{{ kolla_config_path }}]
  template:
    src: "template-overrides.j2"
    dest: "{{ kolla_config_path }}/template-overrides.j2"
  when: pip_cache_enabled | bool or apt_cache_enabled | bool
  tags: build

- name: Add [DEFAULT]/template-override option to kolla-build.conf
  ini_file:
    path: "{{ kolla_config_path }}/kolla-build.conf"
    section: "DEFAULT"
    option: "template_override"
    value: "template-overrides.j2"
  when: pip_cache_enabled | bool or apt_cache_enabled | bool
  tags:
    - build
    - apt_cache

- name: Build all containers
  command: "kolla-build --profile {{ kolla_build_profile }}"
  args:
    chdir: "{{ kolla_config_path }}"
  changed_when: false
  tags: build
